apiVersion: v1
kind: Pod
metadata:
  name: animals-bear
  labels:
    app: animals
spec:
  containers:
  - name: bear
    image: supergiantkir/animals:bear
    ports:
    - containerPort: 80
type: LoadBalancer


apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-test
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 
  template: 
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:mainline-alpine:latest
        ports:
        - containerPort: 80