apiVersion: v1
kind: Pod
metadata:
  name: animals-bear
  labels:
    app: animals
spec:
  containers:
  - name: bear
    image: supergiantkir/animals:bear
    ports:
    - containerPort: 80
type: LoadBalancer
